source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'GlideDemo_iOS' do
    platform :ios, '12.0'
    pod 'GlideEngine', :path => '../'
end

target 'GlideDemo_macOS' do
    platform :macos, '10.13'
    pod 'GlideEngine', :path => '../'
end

target 'GlideDemo_tvOS' do
    platform :tvos, '12.0'
    pod 'GlideEngine', :path => '../'
end
